# Generated by Django 5.1.3 on 2024-11-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_date_added_alter_listing_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
